[package]
name = "game-installer"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31.0", features = ["default"] }
egui-phosphor = "0.9"
rfd = "0.15.2"

[profile.release]
# Options chosen to reduce binary size.
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
