name = "AIGL Test"

[python]
version = "3.13"
venv = "single"

[game]
url = "https://github.com/jl-wynen/aigl_test_game.git"
base_config_in_repo = "path/in/game/config.toml"
launch_args = ["test_game", "{config}"]  # passed to `python -m`

[bot]
template_url = "https://github.com/jl-wynen/aigl_test_bot.git"

# always present:
#id = { type = "string", var = "BOT_ID" }
#name = { type = "string", var = "BOT_NAME" }
[bot.template_args]
# 'colour' or 'color' gets special handling in launcher
color = { type = "color", display = "Color", var = "BOT_COLOR" }

[players]
mode = "free-for-all"
n_min = 2
