name = "Supremacy"

[python]
version = "3.12"
venv = "single"

[game]
url = "https://github.com/jl-wynen/supremacy.git"
base_config_in_repo = "config.toml"
launch_args = ["supremacy", "{config}"]

[bot]
template_url = "https://github.com/jl-wynen/supremacy_ai.git"

# always present:
[bot.template_args]
color = { type = "color", display = "Color", var = "color" }

[players]
mode = "free-for-all"
n_min = 2
n_initial = 10
