name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:

  website:
    name: Publish the website

    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: JamesIves/github-pages-deploy-action@v4
        id: deployment
        with:
          folder: website
          clean-exclude: resources/*

  format:
    name: Formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1.1.1

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
        with:
          components: clippy
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Cargo clippy
        run: cargo clippy -- -Dwarnings

  test:
    name: Test (${{ matrix.os }})
    needs: [ format, clippy ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04 }
          - { os: macos-15 }
          - { os: windows-2025 }
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Install mold
        uses: rui314/setup-mold@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Configure Git
        run: |
          git config --global user.name "AIGL Test"
          git config --global user.email "test@aigl.com"
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
